allow_remote_control yes
include ./theme.conf
#include dracula.conf
#map ctrl+shift+r send_text application \033[88;5u
#map ctrl+RIGHT_BRACKET change_font_size all +2.0
map ctrl+shift+n discard_event

set enable-bracketed-paste off

paste_actions quote-urls-at-prompt,confirm

map ctrl+shift+v no_op


# BEGIN_KITTY_THEME
# Dracula
include current-theme.conf
# END_KITTY_THEME
